language: android
android:
  components:
    - tools
    - platform-tools
    - build-tools-23.0.3
    - android-23

env:
  matrix:
    - ANDROID_TARGET=android-23  ANDROID_ABI=armeabi-v7a

before_install:
    - chmod +x gradlew

script:
    - ./gradlew build connectedCheck